### ISSUE TITLE
Deadlink reference entities

### ISSUE THREAD

**Issue by Doodoune** [akeneo/pim-helpcenter#503]
https://help.akeneo.com/pim/serenity/articles/manage-reference-entities.html#delete-a-reference-entity

Link "delete the records of this reference entity" refers to https://help.akeneo.com/pim/serenity/articles/enrich-your-reference-entity-records.md (ERROR 404)

![screenshot_10](https://user-images.githubusercontent.com/34027529/75462430-8a5b0f00-5984-11ea-9207-964a890b4c49.png)

**Comment by morganen** [comment]
Done! Thanks!

**Comment by Doodoune** [comment]
Hi @morganen,

This issue is still there - the link https://help.akeneo.com/pim/serenity/articles/enrich-your-reference-entity-records#delete-records.html is in error 404.

I reopen the ticket :)

**Comment by LaureBro** [comment]
Hello Elodie, I've checked the link in the article it's working fine, It's not linking to https://help.akeneo.com/pim/serenity/articles/enrich-your-reference-entity-records#delete-records.html, it's linking to https://help.akeneo.com/pim/serenity/articles/enrich-your-reference-entity-records.html#delete-records.
